name: Django CI (docker-compose)

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build-and-check:
    runs-on: ubuntu-latest

    steps:
      # 1. Клонируем репозиторий
      - name: Check out repository
        uses: actions/checkout@v3

      # 2. Запускаем docker-compose в фоновом режиме
      - name: Build and run containers
        run: docker-compose up -d --build

      # 3. Даем время сервисам на инициализацию 
      #    (MySQL + Django) - обычно хватает 15-30 секунд
      - name: Wait for services to be ready
        run: sleep 15

      # 4. Проверяем, что Django-сервер отвечает без ошибок на http://localhost:8000/
      - name: Check Django server
        run: curl --fail http://localhost:8000/ || exit 1

      # 5. Останавливаем контейнеры
      - name: Shutdown
        if: always()
        run: docker-compose down
