name: Django CI (docker-compose)

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build-and-check:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build and run containers
        run: docker-compose up -d --build

      - name: Wait for services to be ready
        run: sleep 15

      - name: Check Django server
        run: curl --fail http://localhost:8000/ || exit 1

      - name: Shutdown
        if: always()
        run: docker-compose down
