name: Django CI (docker-compose)

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build-and-check:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      # Настраиваем Buildx (требуется для docker/compose-action)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Запускаем docker-compose через официальный action
      - name: Compose up
        uses: docker/compose-action@v2
        with:
          files: docker-compose.yml
          build: true
          up: true
          detach: true

      - name: Wait for services to be ready
        run: sleep 15

      - name: Check Django server
        run: curl --fail http://localhost:8000/ || exit 1

      - name: Compose down
        uses: docker/compose-action@v2
        with:
          files: docker-compose.yml
          down: true
