name: Django CI (SQLite, no Docker)

on:
  push:
    branches: [ "main", "mysql_test" ]
  pull_request:

jobs:
  build-and-check:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: mydb
          MYSQL_USER: myuser
          MYSQL_PASSWORD: mypass
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping -h localhost -proot"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3


    steps:
      # 1. Забираем код
      - name: Check out repository
        uses: actions/checkout@v3

      # 2. Устанавливаем Python (выберите нужную версию)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # 3. Устанавливаем зависимости
      - name: Install dependencies
        run: pip install --upgrade pip && pip install django && pip install mysqlclient

      # 4. Применяем миграции (создание/обновление SQLite-базы)
      - name: Migrate
        run: python app/manage.py migrate

      # 5. Запускаем сервер в фоне, ждём пару секунд и проверяем curl
      - name: Check server
        run: |
          python app/manage.py runserver 0.0.0.0:8000 &
          sleep 5
          curl --fail http://127.0.0.1:8000/ || exit 1

      # (Опционально) можно добавить шаг тестов, если есть
      # - name: Run tests
      #   run: python manage.py test
